export default {
  loading: false,
  pants: {
    brands: ["Levi's", "Wrangler", "Calvin Klein", "Tommy Hilfiger", "GAP"],
    colors: [
      "Red",
      "Blue",
      "Green",
      "Yellow",
      "Black",
      "White",
      "Pink",
      "Orange",
      "Purple",
      "Gray",
    ],
    items: [
      "stylishPants",
      "comfyJeans",
      "smartTrousers",
      "coolJoggers",
      "classicChinos",
      "trendyShorts",
      "urbanPants",
      "casualSlacks",
    ],
    sizes: ["S", "M", "L", "XL"],
  },
  shirts: {
    brands: ["Nike", "Adidas", "Puma", "Under Armour", "Gucci"],
    colors: [
      "Red",
      "Blue",
      "Green",
      "Yellow",
      "Black",
      "White",
      "Pink",
      "Orange",
      "Purple",
      "Gray",
    ],
    items: [
      "niceTshirt",
      "wowTshirt",
      "coolShirt",
      "trendyTop",
      "classicShirt",
      "sportyTee",
      "urbanShirt",
      "casualTop",
    ],
    sizes: ["S", "M", "L", "XL"],
  },
  shoes: {
    brands: ["Nike", "Adidas", "Reebok", "Converse", "New Balance"],
    colors: [
      "Red",
      "Blue",
      "Green",
      "Yellow",
      "Black",
      "White",
      "Pink",
      "Orange",
      "Purple",
      "Gray",
    ],
    items: [
      "sportySneakers",
      "classicShoes",
      "trendyBoots",
      "urbanTrainers",
      "comfyLoafers",
      "coolSlipOns",
      "stylishHeels",
      "casualSandals",
    ],
    sizes: [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
  },
};
